# Generated by Django 4.2.4 on 2023-08-18 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("playlists", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="music",
            name="singer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="musics",
                to="playlists.singer",
            ),
        ),
    ]
